# -*- coding: utf-8 -*-
"""2.1 - Reto 1(final) .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xv9QeAZi-oPZ5LIHwxD3N1d5NBiY8J3T
"""

SalarioBase, HorasExtras, Bonificaciones = input().split()

SalarioBase = float(SalarioBase)
CantidadHorasExtras = int(HorasExtras)
CantidadBonificaciones = int(Bonificaciones)

ValorHoraNormal = SalarioBase / 192

if CantidadHorasExtras>0:
  ValorHoraExtra = (ValorHoraNormal * ((25 / 100)+1.0)) * CantidadHorasExtras
else:
  ValorHoraExtra = 0

if CantidadBonificaciones==1:
  ValorBonificaciones = (SalarioBase * (5 / 100)) * CantidadBonificaciones
else:
  ValorBonificaciones = 0

SalarioTotal = SalarioBase + ValorHoraExtra + ValorBonificaciones

PlanObligatorioDeSalud = SalarioTotal * (3.5 / 100)
AportePension = SalarioTotal * (4 / 100)
CajaDeCompensacion = SalarioTotal * (1 / 100)

Descuentos=PlanObligatorioDeSalud+AportePension+CajaDeCompensacion
SalarioFinal = SalarioTotal - Descuentos

print(round(SalarioFinal,1))