# -*- coding: utf-8 -*-
"""2.1 - Reto 2(final).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ujaq5lUU8_Gw00oD9cOzYrQphgPhUTWo
"""

Distancia, VelocidadPermitida, Tiempo = input().split()

DistanciaCamaras = int(Distancia)
VelocidadPermitida = int(VelocidadPermitida)
TiempoConductor = int(Tiempo)
  
DistanciaCamaras= DistanciaCamaras *(1 / 1000)
TiempoConductor= TiempoConductor *(1 / 3600)

VelocidadConductor = DistanciaCamaras / TiempoConductor
VelocidadExcedidaEn20 = VelocidadPermitida + (VelocidadPermitida *(20 /100))

if VelocidadConductor <= VelocidadPermitida:
  print("OK")
elif VelocidadConductor < VelocidadExcedidaEn20:
  print("MULTA")
elif VelocidadConductor>0 and VelocidadExcedidaEn20 > 0 and VelocidadConductor >= VelocidadExcedidaEn20:
  print("CURSO SENSIBILIZACION")
elif VelocidadPermitida < 0 or TiempoConductor < 0 :
  print("ERROR")