# -*- coding: utf-8 -*-
"""3.1 - Reto 3(final).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yCE7Cd2x7xkar9KZiSQb4Nyj_O6cdltU
"""

Bicicletas = []
NumeroDeBicicletas = int(input())

for b in range(NumeroDeBicicletas):
  Bicicletas.append(input().split())

Calificacion = ""
for Cicla in Bicicletas:
  Calificacion = ""
  if int(Cicla[0])>= 240 and int(Cicla[0])<= 300:
    if int(Cicla[1])>= 160 and int(Cicla[1])<= 180:
      if int(Cicla[2])>= 240 and int(Cicla[2])<= 275:
        if int(Cicla[3])>=0 and int(Cicla[3])<= 50:
          Calificacion = "aprobada"
        if Calificacion == "aprobada":
          break
  
if Calificacion == "aprobada":
  print(Cicla[4])
else:
  print("NO DISPONIBLE")